# Generated by Django 5.2.7 on 2025-10-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('duracao', models.CharField(max_length=50)),
                ('grau', models.CharField(choices=[('Bachelor', 'Licenciatura / Bachelor'), ('Master', 'Mestrado / Master'), ('PhD', 'Doutoramento / PhD')], max_length=20)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='universidades.universidade')),
            ],
        ),
    ]
