# Generated by Django 5.2.7 on 2025-10-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('universidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='universidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidades.universidade'),
        ),
    ]
